; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -std=gnu++17 
build_unflags = -std=gnu++11 ;default for arduino framework, needs to be removed!!
lib_deps = 
	https://github.com/playfultechnology/esp32-eyes
	olikRaus/U8g2 ;dependancy for ESP EYES
	bblanchon/ArduinoJson@^7.2.2 ;json parsing
